"""
routers/onboarding.py

Self-service onboarding: creates business + first store atomically.
POST /onboarding/business   — requires authenticated user (JWT)
POST /onboarding/store      — add additional store to existing business
"""
from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from dependencies import get_current_user, supabase
from services.subscription_service import SubscriptionService
from utils.response import api_response

router = APIRouter(prefix="/onboarding", tags=["onboarding"])
logger = logging.getLogger("ice_breaker.onboarding")


# ── Request models ────────────────────────────────────────────────────────────

class CreateBusinessRequest(BaseModel):
    business_name: str = Field(..., min_length=2, max_length=100)
    store_name: Optional[str] = Field(None, description="Defaults to business_name if omitted")
    state_code: str = Field("XX", min_length=2, max_length=4, description="e.g. KL, MH, TN")
    plan: str = Field("basic")


class AddStoreRequest(BaseModel):
    store_name: str = Field(..., min_length=2, max_length=100)
    state_code: str = Field("XX", min_length=2, max_length=4)


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/business")
async def create_business(
    body: CreateBusinessRequest,
    user=Depends(get_current_user),
):
    """
    Step 1: Creates a new business + first store atomically.
    Automatically:
      - Generates store_code
      - Links the calling user as owner
      - Seeds a 7-day free trial subscription
    """
    # Guard: user must not already own a business (optional — remove for multi-business)
    existing = (
        supabase.table("user_businesses")
        .select("business_id")
        .eq("user_id", user.id)
        .eq("role", "owner")
        .limit(1)
        .execute()
    )
    if existing.data:
        raise HTTPException(
            status_code=409,
            detail="You already own a business. Use POST /onboarding/store to add more stores.",
        )

    try:
        result = supabase.rpc(
            "create_business_with_store",
            {
                "p_payload": {
                    "user_id": user.id,
                    "business_name": body.business_name,
                    "store_name": body.store_name or body.business_name,
                    "state_code": body.state_code.upper(),
                    "plan": body.plan,
                }
            },
        ).execute()

        data = result.data
        if not data:
            raise HTTPException(status_code=500, detail="Onboarding RPC returned empty response")

        logger.info(
            "onboarding_business_created user_id=%s business_id=%s store_id=%s",
            user.id, data.get("business_id"), data.get("store_id"),
        )
        return api_response(
            success=True,
            message=(
                f"Business created! Your store code is {data.get('store_code')}. "
                f"7-day free trial started."
            ),
            data=data,
            status_code=201,
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("onboarding_business_failed user_id=%s reason=%s", user.id, exc)
        raise HTTPException(status_code=500, detail=str(exc))


@router.post("/store")
async def add_store(
    body: AddStoreRequest,
    user=Depends(get_current_user),
):
    """
    Add an additional store to the user's existing business.
    The calling user must be owner or admin of the business.
    """
    # Fetch business + role
    biz = (
        supabase.table("user_businesses")
        .select("business_id, role")
        .eq("user_id", user.id)
        .in_("role", ["owner", "admin"])
        .limit(1)
        .execute()
    )
    if not biz.data:
        raise HTTPException(status_code=403, detail="Only owner/admin can add stores")

    business_id = biz.data[0]["business_id"]

    try:
        # Insert store — store_code auto-generated by DB trigger
        store_resp = (
            supabase.table("stores")
            .insert({
                "business_id": business_id,
                "store_name": body.store_name,
                "state_code": body.state_code.upper(),
                "is_main_store": False,
                "is_active": True,
            })
            .execute()
        )
        store = store_resp.data[0]
        store_id = store["store_id"]

        # Grant owner access
        supabase.table("user_store_access").insert({
            "user_id": user.id,
            "store_id": store_id,
            "role": "owner",
            "can_manage_inventory": True,
            "can_manage_ledger": True,
            "can_view_reports": True,
            "can_post_invoices": True,
            "can_manage_purchases": True,
        }).execute()

        # Seed trial
        SubscriptionService.seed_trial(store_id, business_id)

        logger.info(
            "onboarding_store_created user_id=%s business_id=%s store_id=%s",
            user.id, business_id, store_id,
        )
        return api_response(
            success=True,
            message=f"Store '{body.store_name}' created. Code: {store.get('store_code')}. 7-day trial started.",
            data={
                "store_id": store_id,
                "store_code": store.get("store_code"),
                "business_id": business_id,
            },
            status_code=201,
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("onboarding_store_failed user_id=%s reason=%s", user.id, exc)
        raise HTTPException(status_code=500, detail=str(exc))
